shell:
    python manage.py shell

makemigrations app:
    python manage.py makemigrations {{ app }}

migrate:
    python manage.py migrate

runserver:
    python manage.py runserver

startapp app:
    python manage.py startapp {{ app }}

createsuperuser:
    python manage.py createsuperuser


